import { FC, PropsWithChildren } from "react";
import Head from "next/head";

import styles from "./MainLayout.module.css";
import { NavBar } from "../NavBar";

const MainLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>My First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <main className={styles.main}>{children}</main>
    </>
  );
};

export default MainLayout;
